### ISSUE TITLE
Git Action 를 통한 CI 구현

### ISSUE THREAD

**Issue by kim1387** [h-jjang/bauction#25]
### 제안 배경
커밋을 하다 보면 깜박 하고 (코드 컨벤션에 의한)코드 정렬을 안 하기도 하고 test 코드를 작성하는 것을 깜박 하기도 한다.
프로젝트 초반에는 빠르게 진행되기 위해서는 어쩔 수 없다고 생각할 수 도 있다.
하지만 test코드를 작성하지 않으면 프로젝트를 진행할 수록 오류를 찾기도 힘들고 진행 속도는 느려진다. 

이를 막기 위해서 ci를 통해 test coverage를 측정하여 test code를 강제로 작성하도록 하고 
코드 정렬을 잊어버리면 git에서 코드 정렬을 할 수 있도록 한다.

### TODO
- [ ] git action을 통한 코드 자동 정렬
- [ ] git action을 통한 test code 강제화
- [x] naver code convention 추가해서 깃에 올리고 팀원에게 말하기
[해당 블로그를 참고하고 xml파일은 건들 필요 없음](https://iamtaehoon.tistory.com/191)

**Comment by DPS0340** [comment]
배포 자동화도 일정 여유로우시면 해보시면 좋을 듯 합니다 ㅎㅎ
